app = "voicebbs"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 5060
  protocol = "udp"

  [[services.ports]]
    port = 5060
    handlers = ["udp"]